[20170313-085432]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='1', dadoSincronizacao='123456', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.
[20170313-085432]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170313-085432]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170313-085432]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170313-085432]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170313-085432]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170313-085432]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170313-085432]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170313-085432]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170313-085432]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170313-085432]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-085432]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170313-085432]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170313-085432]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-085432]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170313-085432]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170313-085432]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170313-085432]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170313-085432]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170313-085432]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170313-085432]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170313-085432]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170313-085432]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170313-085432]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170313-085432]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
[20170313-085432]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170313-085432]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170313-085432]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170313-085432]: 	at java.lang.Thread.run(Thread.java:662)
[20170313-085432]: Caused by: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.
[20170313-085432]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:47)
[20170313-085432]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170313-085432]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170313-085432]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170313-085432]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170313-085432]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170313-085432]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170313-085432]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170313-085432]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170313-085432]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170313-085432]: 	... 26 more
[20170313-085432]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'CALI0030'.
[20170313-085432]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170313-085432]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170313-085432]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170313-085432]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170313-085432]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170313-085432]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170313-085432]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170313-085432]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170313-085432]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170313-085432]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-085432]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-085432]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:38)
[20170313-085432]: 	... 35 more
[20170313-085432]: .
[20170313-090258]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='1', dadoSincronizacao='123456', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.
[20170313-090258]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170313-090258]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170313-090258]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170313-090258]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170313-090258]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170313-090258]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170313-090258]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170313-090258]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170313-090258]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170313-090258]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-090258]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170313-090258]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170313-090258]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-090258]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170313-090258]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170313-090258]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170313-090258]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170313-090258]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170313-090258]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170313-090258]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170313-090258]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170313-090258]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170313-090258]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170313-090258]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170313-090258]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170313-090258]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170313-090258]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170313-090258]: 	at java.lang.Thread.run(Thread.java:662)
[20170313-090258]: Caused by: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.
[20170313-090258]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:47)
[20170313-090258]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170313-090258]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170313-090258]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170313-090258]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170313-090258]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170313-090258]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170313-090258]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170313-090258]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170313-090258]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170313-090258]: 	... 26 more
[20170313-090258]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'CALI0030'.
[20170313-090258]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170313-090258]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170313-090258]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170313-090258]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170313-090258]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170313-090258]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170313-090258]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170313-090258]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170313-090258]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170313-090258]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-090258]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-090258]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:38)
[20170313-090258]: 	... 35 more
[20170313-090258]: .
[20170313-091158]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='1', dadoSincronizacao='123456', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.
[20170313-091158]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170313-091158]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170313-091158]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170313-091158]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170313-091158]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170313-091158]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170313-091158]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170313-091158]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170313-091158]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170313-091158]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-091158]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170313-091158]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170313-091158]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-091158]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170313-091158]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170313-091158]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170313-091158]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170313-091158]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170313-091158]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170313-091158]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170313-091158]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170313-091158]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170313-091158]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170313-091158]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
[20170313-091158]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170313-091158]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170313-091158]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170313-091158]: 	at java.lang.Thread.run(Thread.java:662)
[20170313-091158]: Caused by: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.
[20170313-091158]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:47)
[20170313-091158]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170313-091158]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170313-091158]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170313-091158]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170313-091158]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170313-091158]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170313-091158]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170313-091158]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170313-091158]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170313-091158]: 	... 26 more
[20170313-091158]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'CALI0030'.
[20170313-091158]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170313-091158]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170313-091158]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170313-091158]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170313-091158]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170313-091158]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170313-091158]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170313-091158]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170313-091158]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170313-091158]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-091158]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-091158]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:38)
[20170313-091158]: 	... 35 more
[20170313-091158]: .
[20170313-091825]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='1', dadoSincronizacao='123456', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.
[20170313-091825]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170313-091825]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170313-091825]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170313-091825]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170313-091825]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170313-091825]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170313-091825]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170313-091825]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170313-091825]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170313-091825]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-091825]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170313-091825]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170313-091825]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-091825]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170313-091825]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170313-091825]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170313-091825]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170313-091825]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170313-091825]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170313-091825]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170313-091825]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170313-091825]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170313-091825]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170313-091825]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170313-091825]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170313-091825]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170313-091825]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170313-091825]: 	at java.lang.Thread.run(Thread.java:662)
[20170313-091825]: Caused by: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.
[20170313-091825]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:47)
[20170313-091825]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170313-091825]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170313-091825]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170313-091825]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170313-091825]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170313-091825]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170313-091825]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170313-091825]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170313-091825]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170313-091825]: 	... 26 more
[20170313-091825]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'CALI0030'.
[20170313-091825]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170313-091825]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170313-091825]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170313-091825]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170313-091825]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170313-091825]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170313-091825]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170313-091825]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170313-091825]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170313-091825]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-091825]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-091825]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:38)
[20170313-091825]: 	... 35 more
[20170313-091825]: .
[20170313-091900]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='1', dadoSincronizacao='123456', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.
[20170313-091900]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170313-091900]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170313-091900]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170313-091900]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170313-091900]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170313-091900]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170313-091900]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170313-091900]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170313-091900]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170313-091900]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-091900]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170313-091900]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170313-091900]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-091900]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170313-091900]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170313-091900]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170313-091900]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170313-091900]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170313-091900]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170313-091900]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170313-091900]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170313-091900]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170313-091900]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170313-091900]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
[20170313-091900]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170313-091900]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170313-091900]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170313-091900]: 	at java.lang.Thread.run(Thread.java:662)
[20170313-091900]: Caused by: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.
[20170313-091900]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:48)
[20170313-091900]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170313-091900]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170313-091900]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170313-091900]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170313-091900]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170313-091900]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170313-091900]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170313-091900]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170313-091900]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170313-091900]: 	... 26 more
[20170313-091900]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'CALI0030'.
[20170313-091900]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170313-091900]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170313-091900]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170313-091900]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170313-091900]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170313-091900]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170313-091900]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170313-091900]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170313-091900]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170313-091900]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-091900]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-091900]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:38)
[20170313-091900]: 	... 35 more
[20170313-091900]: .
[20170313-091916]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='3', dadoSincronizacao='123456', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL orquestrador.pmltCargaDistribuidor01(?)} ERRO: Login failed for user 'CALI0030'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL orquestrador.pmltCargaDistribuidor01(?)} ERRO: Login failed for user 'CALI0030'.
[20170313-091916]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170313-091916]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170313-091916]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170313-091916]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170313-091916]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170313-091916]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170313-091916]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170313-091916]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170313-091916]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170313-091916]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-091916]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170313-091916]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170313-091916]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-091916]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170313-091916]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170313-091916]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170313-091916]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170313-091916]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170313-091916]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170313-091916]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170313-091916]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170313-091916]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170313-091916]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170313-091916]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170313-091916]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170313-091916]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170313-091916]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170313-091916]: 	at java.lang.Thread.run(Thread.java:662)
[20170313-091916]: Caused by: util.BancoDadosException: QUERY: {CALL orquestrador.pmltCargaDistribuidor01(?)} ERRO: Login failed for user 'CALI0030'.
[20170313-091916]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:48)
[20170313-091916]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170313-091916]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170313-091916]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170313-091916]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170313-091916]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170313-091916]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170313-091916]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170313-091916]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170313-091916]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170313-091916]: 	... 26 more
[20170313-091916]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'CALI0030'.
[20170313-091916]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170313-091916]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170313-091916]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170313-091916]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170313-091916]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170313-091916]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170313-091916]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170313-091916]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170313-091916]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170313-091916]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-091916]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-091916]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:38)
[20170313-091916]: 	... 35 more
[20170313-091916]: .
[20170313-094853]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='1', dadoSincronizacao='012345678901234', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.
[20170313-094853]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170313-094853]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170313-094853]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170313-094853]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170313-094853]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170313-094853]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170313-094853]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170313-094853]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170313-094853]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170313-094853]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-094853]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170313-094853]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170313-094853]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-094853]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170313-094853]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170313-094853]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170313-094853]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170313-094853]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170313-094853]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170313-094853]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170313-094853]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170313-094853]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170313-094853]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170313-094853]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
[20170313-094853]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170313-094853]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170313-094853]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170313-094853]: 	at java.lang.Thread.run(Thread.java:662)
[20170313-094853]: Caused by: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Login failed for user 'CALI0030'.
[20170313-094853]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:48)
[20170313-094853]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170313-094853]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170313-094853]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170313-094853]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170313-094853]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170313-094853]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170313-094853]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170313-094853]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170313-094853]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170313-094853]: 	... 26 more
[20170313-094853]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'CALI0030'.
[20170313-094853]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170313-094853]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170313-094853]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170313-094853]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170313-094853]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170313-094853]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170313-094853]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170313-094853]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170313-094853]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170313-094853]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-094853]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-094853]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:38)
[20170313-094853]: 	... 35 more
[20170313-094853]: .
[20170313-095453]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='3', dadoSincronizacao='123456', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL orquestrador.pmltCargaDistribuidor01(?)} ERRO: Login failed for user 'CALI0030'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL orquestrador.pmltCargaDistribuidor01(?)} ERRO: Login failed for user 'CALI0030'.
[20170313-095453]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170313-095453]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170313-095453]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170313-095453]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170313-095453]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170313-095453]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170313-095453]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170313-095453]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170313-095453]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170313-095453]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-095453]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170313-095453]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170313-095453]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-095453]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170313-095453]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170313-095453]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170313-095453]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170313-095453]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170313-095453]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170313-095453]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170313-095453]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170313-095453]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170313-095453]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170313-095453]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
[20170313-095453]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170313-095453]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170313-095453]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170313-095453]: 	at java.lang.Thread.run(Thread.java:662)
[20170313-095453]: Caused by: util.BancoDadosException: QUERY: {CALL orquestrador.pmltCargaDistribuidor01(?)} ERRO: Login failed for user 'CALI0030'.
[20170313-095453]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:48)
[20170313-095453]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170313-095453]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170313-095453]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170313-095453]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170313-095453]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170313-095453]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170313-095453]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170313-095453]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170313-095453]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170313-095453]: 	... 26 more
[20170313-095453]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'CALI0030'.
[20170313-095453]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170313-095453]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170313-095453]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170313-095453]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170313-095453]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170313-095453]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170313-095453]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170313-095453]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170313-095453]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170313-095453]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-095453]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-095453]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:38)
[20170313-095453]: 	... 35 more
[20170313-095453]: .
[20170313-095719]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='5', dadoSincronizacao='123456', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL orquestrador.pmltCargaCotistas01(?)} ERRO: Login failed for user 'CALI0030'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL orquestrador.pmltCargaCotistas01(?)} ERRO: Login failed for user 'CALI0030'.
[20170313-095719]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170313-095719]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170313-095719]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170313-095719]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170313-095719]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170313-095719]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170313-095719]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170313-095719]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170313-095719]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170313-095719]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-095719]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170313-095719]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170313-095719]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-095719]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170313-095719]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170313-095719]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170313-095719]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170313-095719]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170313-095719]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170313-095719]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170313-095719]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170313-095719]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170313-095719]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170313-095719]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
[20170313-095719]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170313-095719]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170313-095719]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170313-095719]: 	at java.lang.Thread.run(Thread.java:662)
[20170313-095719]: Caused by: util.BancoDadosException: QUERY: {CALL orquestrador.pmltCargaCotistas01(?)} ERRO: Login failed for user 'CALI0030'.
[20170313-095719]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:48)
[20170313-095719]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170313-095719]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170313-095719]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170313-095719]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170313-095719]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170313-095719]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170313-095719]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170313-095719]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170313-095719]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170313-095719]: 	... 26 more
[20170313-095719]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'CALI0030'.
[20170313-095719]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170313-095719]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170313-095719]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170313-095719]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170313-095719]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170313-095719]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170313-095719]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170313-095719]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170313-095719]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170313-095719]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-095719]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-095719]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:38)
[20170313-095719]: 	... 35 more
[20170313-095719]: .
[20170313-120327]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', Mensagem da Exceção:'java.lang.NullPointerException', StackTrace:=javax.servlet.ServletException: java.lang.NullPointerException
[20170313-120327]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170313-120327]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170313-120327]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170313-120327]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170313-120327]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170313-120327]: 	at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:507)
[20170313-120327]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
[20170313-120327]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170313-120327]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170313-120327]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-120327]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170313-120327]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170313-120327]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-120327]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170313-120327]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170313-120327]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170313-120327]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170313-120327]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170313-120327]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170313-120327]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170313-120327]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170313-120327]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170313-120327]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170313-120327]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
[20170313-120327]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170313-120327]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170313-120327]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170313-120327]: 	at java.lang.Thread.run(Thread.java:662)
[20170313-120327]: Caused by: java.lang.NullPointerException
[20170313-120327]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:22)
[20170313-120327]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170313-120327]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170313-120327]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170313-120327]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170313-120327]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170313-120327]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170313-120327]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170313-120327]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170313-120327]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170313-120327]: 	... 26 more
[20170313-120327]: .
[20170313-120339]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='1', dadoSincronizacao='00000000000191', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Could not find stored procedure 'orquestrador.pMltCargaEmpresa01'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Could not find stored procedure 'orquestrador.pMltCargaEmpresa01'.
[20170313-120339]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170313-120339]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170313-120339]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170313-120339]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170313-120339]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170313-120339]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170313-120339]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170313-120339]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170313-120339]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170313-120339]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-120339]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170313-120339]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170313-120339]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-120339]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170313-120339]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170313-120339]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170313-120339]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170313-120339]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170313-120339]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170313-120339]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170313-120339]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170313-120339]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170313-120339]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170313-120339]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170313-120339]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170313-120339]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170313-120339]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170313-120339]: 	at java.lang.Thread.run(Thread.java:662)
[20170313-120339]: Caused by: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaEmpresa01(?)} ERRO: Could not find stored procedure 'orquestrador.pMltCargaEmpresa01'.
[20170313-120339]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:48)
[20170313-120339]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170313-120339]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170313-120339]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170313-120339]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170313-120339]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170313-120339]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170313-120339]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170313-120339]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170313-120339]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170313-120339]: 	... 26 more
[20170313-120339]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Could not find stored procedure 'orquestrador.pMltCargaEmpresa01'.
[20170313-120339]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170313-120339]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170313-120339]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170313-120339]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170313-120339]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170313-120339]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170313-120339]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170313-120339]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170313-120339]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170313-120339]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-120339]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-120339]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:38)
[20170313-120339]: 	... 35 more
[20170313-120339]: .
[20170313-120428]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='2', dadoSincronizacao='0855', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaFundos01(?)} ERRO: Could not find stored procedure 'orquestrador.pMltCargaFundos01'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaFundos01(?)} ERRO: Could not find stored procedure 'orquestrador.pMltCargaFundos01'.
[20170313-120428]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170313-120428]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170313-120428]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170313-120428]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170313-120428]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170313-120428]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170313-120428]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170313-120428]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170313-120428]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170313-120428]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-120428]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170313-120428]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170313-120428]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-120428]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170313-120428]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170313-120428]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170313-120428]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170313-120428]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170313-120428]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170313-120428]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170313-120428]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170313-120428]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170313-120428]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170313-120428]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170313-120428]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170313-120428]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170313-120428]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170313-120428]: 	at java.lang.Thread.run(Thread.java:662)
[20170313-120428]: Caused by: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaFundos01(?)} ERRO: Could not find stored procedure 'orquestrador.pMltCargaFundos01'.
[20170313-120428]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:48)
[20170313-120428]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170313-120428]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170313-120428]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170313-120428]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170313-120428]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170313-120428]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170313-120428]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170313-120428]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170313-120428]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170313-120428]: 	... 26 more
[20170313-120428]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Could not find stored procedure 'orquestrador.pMltCargaFundos01'.
[20170313-120428]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170313-120428]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170313-120428]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170313-120428]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170313-120428]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170313-120428]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170313-120428]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170313-120428]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170313-120428]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170313-120428]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-120428]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-120428]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:38)
[20170313-120428]: 	... 35 more
[20170313-120428]: .
[20170313-120514]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='2', dadoSincronizacao='0855', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaFundos01(?)} ERRO: Could not find stored procedure 'orquestrador.pMltCargaFundos01'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaFundos01(?)} ERRO: Could not find stored procedure 'orquestrador.pMltCargaFundos01'.
[20170313-120514]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170313-120514]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170313-120514]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170313-120514]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170313-120514]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170313-120514]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170313-120514]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170313-120514]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170313-120514]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170313-120514]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-120514]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170313-120514]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170313-120514]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-120514]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170313-120514]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170313-120514]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170313-120514]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170313-120514]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170313-120514]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170313-120514]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170313-120514]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170313-120514]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170313-120514]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170313-120514]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170313-120514]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170313-120514]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170313-120514]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170313-120514]: 	at java.lang.Thread.run(Thread.java:662)
[20170313-120514]: Caused by: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaFundos01(?)} ERRO: Could not find stored procedure 'orquestrador.pMltCargaFundos01'.
[20170313-120514]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:48)
[20170313-120514]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170313-120514]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170313-120514]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170313-120514]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170313-120514]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170313-120514]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170313-120514]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170313-120514]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170313-120514]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170313-120514]: 	... 26 more
[20170313-120514]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Could not find stored procedure 'orquestrador.pMltCargaFundos01'.
[20170313-120514]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170313-120514]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170313-120514]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170313-120514]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170313-120514]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170313-120514]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170313-120514]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170313-120514]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170313-120514]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170313-120514]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-120514]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-120514]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:38)
[20170313-120514]: 	... 35 more
[20170313-120514]: .
[20170313-120541]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='2', dadoSincronizacao='123123', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaFundos01(?)} ERRO: Could not find stored procedure 'orquestrador.pMltCargaFundos01'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaFundos01(?)} ERRO: Could not find stored procedure 'orquestrador.pMltCargaFundos01'.
[20170313-120541]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170313-120541]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170313-120541]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170313-120541]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170313-120541]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170313-120541]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170313-120541]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170313-120541]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170313-120541]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170313-120541]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-120541]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170313-120541]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170313-120541]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-120541]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170313-120541]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170313-120541]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170313-120541]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170313-120541]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170313-120541]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170313-120541]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170313-120541]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170313-120541]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170313-120541]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170313-120541]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170313-120541]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170313-120541]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170313-120541]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170313-120541]: 	at java.lang.Thread.run(Thread.java:662)
[20170313-120541]: Caused by: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaFundos01(?)} ERRO: Could not find stored procedure 'orquestrador.pMltCargaFundos01'.
[20170313-120541]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:48)
[20170313-120541]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170313-120541]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170313-120541]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170313-120541]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170313-120541]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170313-120541]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170313-120541]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170313-120541]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170313-120541]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170313-120541]: 	... 26 more
[20170313-120541]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Could not find stored procedure 'orquestrador.pMltCargaFundos01'.
[20170313-120541]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170313-120541]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170313-120541]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170313-120541]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170313-120541]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170313-120541]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170313-120541]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170313-120541]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170313-120541]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170313-120541]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-120541]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-120541]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:38)
[20170313-120541]: 	... 35 more
[20170313-120541]: .
[20170313-120615]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/Sincronizacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='sincronizar', tipoSincronizacao='2', dadoSincronizacao='asdasd', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaFundos01(?)} ERRO: Login failed for user 'CALI0030'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaFundos01(?)} ERRO: Login failed for user 'CALI0030'.
[20170313-120615]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170313-120615]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170313-120615]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170313-120615]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170313-120615]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170313-120615]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170313-120615]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170313-120615]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170313-120615]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170313-120615]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-120615]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170313-120615]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170313-120615]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-120615]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170313-120615]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170313-120615]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170313-120615]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170313-120615]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170313-120615]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170313-120615]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170313-120615]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170313-120615]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170313-120615]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170313-120615]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170313-120615]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170313-120615]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170313-120615]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170313-120615]: 	at java.lang.Thread.run(Thread.java:662)
[20170313-120615]: Caused by: util.BancoDadosException: QUERY: {CALL orquestrador.pMltCargaFundos01(?)} ERRO: Login failed for user 'CALI0030'.
[20170313-120615]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:48)
[20170313-120615]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.sincronizar(ConteudoMenuEntity.java:107)
[20170313-120615]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.SincronizacaoAction.sincronizar(SincronizacaoAction.java:75)
[20170313-120615]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170313-120615]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170313-120615]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170313-120615]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170313-120615]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170313-120615]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170313-120615]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170313-120615]: 	... 26 more
[20170313-120615]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'CALI0030'.
[20170313-120615]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170313-120615]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170313-120615]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170313-120615]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170313-120615]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170313-120615]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170313-120615]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170313-120615]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170313-120615]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170313-120615]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-120615]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-120615]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.SincronizacaoSQLDAO.sincronizar(SincronizacaoSQLDAO.java:38)
[20170313-120615]: 	... 35 more
[20170313-120615]: .
[20170313-120746]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/FiltroImplantacao.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='listar', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL filtro.pSelFiltroImplantacao01()} ERRO: The EXECUTE permission was denied on the object 'pSelFiltroImplantacao01', database 'CALID003', schema 'filtro'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL filtro.pSelFiltroImplantacao01()} ERRO: The EXECUTE permission was denied on the object 'pSelFiltroImplantacao01', database 'CALID003', schema 'filtro'.
[20170313-120746]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170313-120746]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170313-120746]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170313-120746]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170313-120746]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170313-120746]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170313-120746]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170313-120746]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170313-120746]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170313-120746]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-120746]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170313-120746]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170313-120746]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-120746]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170313-120746]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170313-120746]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170313-120746]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170313-120746]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170313-120746]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170313-120746]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170313-120746]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170313-120746]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170313-120746]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170313-120746]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170313-120746]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170313-120746]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170313-120746]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170313-120746]: 	at java.lang.Thread.run(Thread.java:662)
[20170313-120746]: Caused by: util.BancoDadosException: QUERY: {CALL filtro.pSelFiltroImplantacao01()} ERRO: The EXECUTE permission was denied on the object 'pSelFiltroImplantacao01', database 'CALID003', schema 'filtro'.
[20170313-120746]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.ConteudoMenuSQLDAO.obterListaFiltroImplantacao(ConteudoMenuSQLDAO.java:349)
[20170313-120746]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.obterListaFiltroImplantacao(ConteudoMenuEntity.java:83)
[20170313-120746]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.FiltroImplantacaoAction.ListaFiltro(FiltroImplantacaoAction.java:109)
[20170313-120746]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.FiltroImplantacaoAction.listar(FiltroImplantacaoAction.java:50)
[20170313-120746]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170313-120746]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170313-120746]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170313-120746]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170313-120746]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170313-120746]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170313-120746]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170313-120746]: 	... 26 more
[20170313-120746]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The EXECUTE permission was denied on the object 'pSelFiltroImplantacao01', database 'CALID003', schema 'filtro'.
[20170313-120746]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170313-120746]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170313-120746]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170313-120746]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170313-120746]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170313-120746]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170313-120746]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170313-120746]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170313-120746]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170313-120746]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-120746]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-120746]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.ConteudoMenuSQLDAO.obterListaFiltroImplantacao(ConteudoMenuSQLDAO.java:334)
[20170313-120746]: 	... 36 more
[20170313-120746]: .
[20170313-120748]: Ocorreu uma exceção no método processActionPerform., CTRL='null', IP='0:0:0:0:0:0:0:1', contextPath='/calipaadm', URI='/calipaadm/FiltroUsuario.do', Mensagem='Ocorreu uma exceção no método processActionPerform.', Parâmetros:, action='listar', Mensagem da Exceção:'util.BancoDadosException: QUERY: {CALL filtro.pSelFiltroImplantacao01()} ERRO: The EXECUTE permission was denied on the object 'pSelFiltroImplantacao01', database 'CALID003', schema 'filtro'.', StackTrace:=javax.servlet.ServletException: util.BancoDadosException: QUERY: {CALL filtro.pSelFiltroImplantacao01()} ERRO: The EXECUTE permission was denied on the object 'pSelFiltroImplantacao01', database 'CALID003', schema 'filtro'.
[20170313-120748]: 	at org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:545)
[20170313-120748]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:486)
[20170313-120748]: 	at br.com.bradesco.portaladm.apresentacao.AplicacaoPortalRequestProcessor.processActionPerform(AplicacaoPortalRequestProcessor.java:79)
[20170313-120748]: 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
[20170313-120748]: 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1482)
[20170313-120748]: 	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:525)
[20170313-120748]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
[20170313-120748]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
[20170313-120748]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
[20170313-120748]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-120748]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.CharEncodeFilter.doFilter(CharEncodeFilter.java:37)
[20170313-120748]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
[20170313-120748]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
[20170313-120748]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
[20170313-120748]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
[20170313-120748]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
[20170313-120748]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
[20170313-120748]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
[20170313-120748]: 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
[20170313-120748]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
[20170313-120748]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
[20170313-120748]: 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
[20170313-120748]: 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
[20170313-120748]: 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
[20170313-120748]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[20170313-120748]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[20170313-120748]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[20170313-120748]: 	at java.lang.Thread.run(Thread.java:662)
[20170313-120748]: Caused by: util.BancoDadosException: QUERY: {CALL filtro.pSelFiltroImplantacao01()} ERRO: The EXECUTE permission was denied on the object 'pSelFiltroImplantacao01', database 'CALID003', schema 'filtro'.
[20170313-120748]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.ConteudoMenuSQLDAO.obterListaFiltroImplantacao(ConteudoMenuSQLDAO.java:349)
[20170313-120748]: 	at br.com.bradesco.custodia.portal.portaladm.negocio.ConteudoMenuEntity.obterListaFiltroImplantacao(ConteudoMenuEntity.java:83)
[20170313-120748]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.FiltroUsuarioAction.listaFiltro(FiltroUsuarioAction.java:158)
[20170313-120748]: 	at br.com.bradesco.custodia.portal.portaladm.apresentacao.FiltroUsuarioAction.listar(FiltroUsuarioAction.java:53)
[20170313-120748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20170313-120748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[20170313-120748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[20170313-120748]: 	at java.lang.reflect.Method.invoke(Method.java:597)
[20170313-120748]: 	at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:280)
[20170313-120748]: 	at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:216)
[20170313-120748]: 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
[20170313-120748]: 	... 26 more
[20170313-120748]: Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The EXECUTE permission was denied on the object 'pSelFiltroImplantacao01', database 'CALID003', schema 'filtro'.
[20170313-120748]: 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
[20170313-120748]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
[20170313-120748]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
[20170313-120748]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
[20170313-120748]: 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
[20170313-120748]: 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
[20170313-120748]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
[20170313-120748]: 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
[20170313-120748]: 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
[20170313-120748]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-120748]: 	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
[20170313-120748]: 	at br.com.bradesco.custodia.portal.portaladm.integracao.ConteudoMenuSQLDAO.obterListaFiltroImplantacao(ConteudoMenuSQLDAO.java:334)
[20170313-120748]: 	... 36 more
[20170313-120748]: .
